org: vicont
app: backend
service: sls-rbi-homework

custom:
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, env:NODE_ENV}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}

plugins:
  - serverless-offline

package:
  include: "*"
  # Problem #1: Return the PLK menu
functions:
  menu:
    description: Return the PLK menu.
    handler: dist/index.menuHandler
    events:
      - http:
          path: menu
          method: GET
  # Problem #2: Add a `GET /cart` endpoint
  cart:
    description: Map PLU to itemId on the user cart.
    handler: dist/index.cartHandler
    events:
      - http:
          path: cart
          method: GET
  # Problem #3 Add a `GET /4pc-chicken/calories` endpoint
  calories:
    description: Compute min & max calories for a 4PC chicken combo.
    handler: dist/index.calorieCounterHandler
    events:
      - http:
          path: 4pc-chicken/calories
          method: GET

