service: sls-rbi-homework

custom:
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, env:NODE_ENV}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}

plugins:
  - serverless-offline

package:
  include: "*"

functions:
  menu:
    description: Called to create an order in NCR.
    handler: dist/index.menuHandler
    events:
      - http:
          path: menu
          method: GET
  # Question #2: Add a `GET /cart` endpoint
  # Question #3 Add a `GET /4pc-chicken/calories` endpoint